### ISSUE TITLE
Open file from widget not working

### ISSUE THREAD

**Issue by alchemiker** [maxistar/TextPad#35]
I always used the TextPad for TXT-files in connection with this Shortcut Manager [FileShortcut](https://github.com/75py/FileShortcut) which I know, is extremely outdated, but it just worked - until recently. I can now neither open existing shortcuts nor new ones properly. When I tap on the shortcut, the "TextPad"-App opens properly, but makes a Toast "File not found" and opens an empty file `newfile.txt` instead of the wished one which is sad. Other file formats in other apps other apps open fine.

**Comment by maxistar** [comment]
hm, interesting could happen due of latest release, I will try to reproduce the issue and fix...

**Comment by maxistar** [comment]
the reason is that android SDK [does not allow files to be opened directly by url anymore](https://developer.android.com/oauth2callback?state=%7B%22csrf_token%22%3A+%22fa5ab7148cb21ed89d47eee66c4264662f399b0dd2c88a09876329d994f5e07e%22%2C+%22return_url%22%3A+%22https%3A%2F%2Fdeveloper.android.com%2Fabout%2Fversions%2F11%2Fprivacy%2Fstorage%22%7D&error_subtype=access_denied&error=interaction_required#media-direct-file-native), instead it allows only using internal file manager, and there is no way to open it without selecting it using file picker. I am thinking about asking user to select file using file picker first time and then to remember it together with the url sent to the application as workaround... e.g. if the file is opened using the file picker has url "content://com.android.externalstorage.documents/document/primary%3ADocuments%2Fwork%2F%D0%B8%D0%B4%D0%B5%D0%B8.md" and the url requested to be openend is "file:///storage/emulated/0/Documents/work/%D0%B8%D0%B4%D0%B5%D0%B8.md" then what I can do - remember that if this url is requested to be open and use the url which we already granted an access. 
Not the most user friendly way, but seems this is only an option to do that...
